global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otelcol'
    static_configs:
      - targets:
        - '10.0.23.61:8889'  # IP of Dev yolo  instance
        - '10.0.26.56:8889'  # IP of Prod Yolo Instance 
        - '10.0.18.4:8889'   # IP of Prod Telegram Bot instance 
        - '10.0.17.41:8889'  # IP of Dev Telegram Bot Instance 

