global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otelcol-dev-yolo'
    static_configs:
      - targets: ['10.0.23.61:8889']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'otelcol-prod-yolo'
    static_configs:
      - targets: ['10.0.26.56:8889']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'otelcol-prod-telegram'
    static_configs:
      - targets: ['10.0.18.4:8889']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http

  - job_name: 'otelcol-dev-telegram'
    static_configs:
      - targets: ['10.0.17.41:8889']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http